### ISSUE TITLE
测试 test-html-parser 的时候有错误,能否提供一些其它例子?

### ISSUE THREAD

**Issue by qokelate** [liigo/html-parser#1]
[code]<a href=\"xxx<a bb=11>x</a>x\" ccc=w>AAA<BR/>BB<H1>CC</H1>DD</a>[/code]

比如这个  我想取得A标签的文本"AAABBDD" 如何取得?

测试您的例子时报以下错误

PS: 不知道怎么贴代码,囧
## Microsoft Visual C++ Debug Library

Debug Assertion Failed!

Program: ...nts\Visual Studio 2010\Projects\CPP\cunese\Compiled\dCURL.exe
File: f:\dd\vctools\crt_bld\self_x86\crt\src\isctype.c
Line: 56

Expression: (unsigned)(c + 1) <= 256

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.
## 中止(A)   重试(R)   忽略(I)   

[/code]

**Comment by liigo** [comment]
先close了，有更详细错误HTML代码请随时留言。
